name: 01 - Blocks

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "Hi there!"
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye-1
        run: | 
          echo "It was nice meeting you!"
          echo "See you soon"
      - name: goodbye-2
        run: echo "GoodBye!"