name: 02 - Triggers

on:
  workflow_dispatch: 
  push:
    branches-ignore:
      - main
      - 'releases/**'
  pull_request: 
    types: 
      - opened
    branches: 
      - main
      - 'releases/**'
    

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Triggering Event
        run: echo "Workflow triggered by ${{github.event_name}} event"
