name: 04 - Actions

on: workflow_dispatch

jobs:
  java-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: java-app
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: build with maven
        run: mvn clean package