name: 08 - Expressions

on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: To get debug logs


jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: inputs.debug 
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: '[debug] Print when triggered from main'
        if: inputs.debug && github.ref_name == 'main'
        run: echo "workflow was triggered from main"
      - name: Greetings
        run: echo "Hi there!"
