name: 13 - Outputs

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - id: build
        name: Build
        run: |
          echo "$GITHUB_OUTPUT"
          echo "artifact=app.jar" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "deploying ${{ needs.build.outputs.artifact }}"