name: 17 - Composite
run-name: 17 - Custom Actions - Composite

on:
  workflow_dispatch:

env:
  working-directory: react-app
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        uses: ./.github/actions/composite
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory }}
      - name: Print setup deps output
        run: |
          echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"
      - name: Build
        run: npm run build